development:
  adapter: mysql2
  encoding: utf8
  database: app_demo_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: app_demo_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: app_demo_production
  host: localhost
  username: root
  password:
